### ISSUE TITLE
how to install the plugin,it doesn't work

### ISSUE THREAD

**Issue by lilyroselily** [stgeneral/redmine-progressive-theme#2]
@stgeneral 

hi，stgeneral 

thanks for provide the plugin.
but when I install it to the redmine plugins folder, it doesn't work normally.
my work environment just like the attachment.
may u check it?
thanks a lot
best regards
![ba6ec8e2-819e-11e6-9b0a-393a0264410d](https://cloud.githubusercontent.com/assets/22336811/19373386/235e091e-91f6-11e6-8131-dfa952b11434.png)

**Comment by stgeneral** [comment]
This is actually not a plug in,  this is a theme and here is the installation instructions http://www.redmine.org/projects/redmine/wiki/Themes. Thank you.
